version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=strongpassword
      - GENERIC_TIMEZONE=Asia/Kolkata
      # 👇 Important for IP access
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=10.30.50.27      # replace with your server’s IP
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:


